services:
  - type: web
    name: video-downloader-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: NODE_VERSION
        value: 18
